apiVersion: batch/v1
kind: Job
metadata:
  name: archon-rl-selfplay
  namespace: archon-rh
spec:
  template:
    spec:
      restartPolicy: Never
      nodeSelector:
        accelerator: nvidia
      containers:
        - name: rl-selfplay
          image: archon-rh/trainer:latest
          command: ["python", "prover/rl/run_selfplay.py", "--config", "orchestration/configs/rl_tiny.yaml", "--walltime", "300"]
          resources:
            limits:
              nvidia.com/gpu: "1"
              cpu: "8"
              memory: 32Gi
