name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -e .[dev]
      - name: Lint
        run: . .venv/bin/activate && ruff check .
      - name: Tests
        run: . .venv/bin/activate && pytest -q
  build-images:
    runs-on: ubuntu-latest
    needs: lint-test
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build Docker images
        run: |
          docker build -f docker/base.Dockerfile -t archon/base .
          docker build -f docker/trainer.Dockerfile -t archon/trainer .
          docker build -f docker/numerics.Dockerfile -t archon/numerics .
          docker build -f docker/lean.Dockerfile -t archon/lean .
